# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2VCz7ZBg3QeV7C-cXU90OEPADngIPDQ
"""

import os

# ZIP file ka naam check kar
files_list = os.listdir('/content/')
print(files_list)

import pandas as pd

df = pd.read_csv('/content/city_day.csv')
print("✅ Dataset Loaded!")
print(f"Shape: {df.shape}")
df.head()

# Shape — rows and columns
print("Shape:", df.shape)

# First 5 rows
print(df.head())

# Last 5 rows
print(df.tail())

# Column names
print("Columns:", df.columns.tolist())

# Data types
print(df.dtypes)

# Basic statistics
print(df.describe())

# Check missing values
print("Missing Values:\n", df.isnull().sum())

# Check duplicate rows
print("Duplicates:", df.duplicated().sum())

import matplotlib.pyplot as plt
import seaborn as sns

# Plot AQI trend over time
df['Date'] = pd.to_datetime(df['Date'])
df.groupby('Date')['AQI'].mean().plot(figsize=(12, 5), color='blue')
plt.title("AQI Trend Over Time")
plt.ylabel("AQI")
plt.xlabel("Date")
plt.show()

# Top 10 most polluted cities
df.groupby('City')['AQI'].mean().sort_values(ascending=False).head(10).plot(
    kind='bar', color='red', figsize=(12, 5))
plt.title("Top 10 Most Polluted Cities")
plt.ylabel("Average AQI")
plt.tight_layout()
plt.show()

# Fill missing AQI values with median
df['AQI'].fillna(df['AQI'].median(), inplace=True)

# Drop rows where City is missing
df.dropna(subset=['City'], inplace=True)

print("Cleaned Shape:", df.shape)
print("Missing Values After Cleaning:\n", df.isnull().sum())

df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
print(df['Year'].value_counts())

pre_covid = df[df['Year'] == 2019]['AQI'].mean()
covid = df[df['Year'] == 2020]['AQI'].mean()

print(f"2019 Avg AQI: {pre_covid:.1f}")
print(f"2020 Avg AQI (COVID): {covid:.1f}")
print(f"Improvement: {pre_covid - covid:.1f} points")

import matplotlib.pyplot as plt
plt.bar(['2019 (Pre-COVID)', '2020 (COVID Lockdown)'],
        [pre_covid, covid], color=['red', 'green'])
plt.title("AQI Before vs During COVID Lockdown")
plt.ylabel("Average AQI")
plt.tight_layout()
plt.show()

import seaborn as sns
import numpy as np

cols = ['PM2.5', 'PM10', 'NO', 'NO2', 'CO', 'SO2', 'O3', 'AQI']
available_cols = [c for c in cols if c in df.columns]

plt.figure(figsize=(10, 8))
corr = df[available_cols].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', square=True)
plt.title("Correlation Between Pollutants and AQI")
plt.tight_layout()
plt.show()

!pip install prophet -q
from prophet import Prophet

delhi = df[df['City'] == 'Delhi'][['Date', 'AQI']].dropna()
delhi.columns = ['ds', 'y']
delhi = delhi.groupby('ds')['y'].mean().reset_index()

model = Prophet(yearly_seasonality=True)
model.fit(delhi)

future = model.make_future_dataframe(periods=365)
forecast = model.predict(future)

model.plot(forecast)
plt.title("Delhi AQI Forecast - Next 1 Year")
plt.show()
print("✅ Forecasting Done!")